name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get rustc version
      id: rustver
      run: echo "rustc=$(rustc -V)" >> "$GITHUB_OUTPUT"
    - name: Cache Cargo registry+git
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-sources-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-sources-

    - name: Cache Cargo target
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('**/Cargo.lock') }}-${{ steps.rustver.outputs.rustc }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

